name: test workflow

defaults:
  run:
    shell: bash

on:
  push: 
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: clone google test
      run: git clone https://github.com/google/googletest.git

    - name: install SDL2
      run: sudo apt-get install libsdl2-dev

    - name: cmake
      run: cmake CMakeLists.txt
    
    - name: make
      run: make

    - name: run tests
      run: ./chip8tests/chip8tests